version: '3'

services:
  grafana:
    image: grafana/grafana
    hostname: grafana
    container_name: grafana
    restart: always

    ports:
        - 3000:3000

    volumes:
      - ./conf/grafana.ini:/etc/grafana/grafana.ini
      - ./csv:/usr/share/grafana/csv
        
# nvim et sw=2 ts=2
